// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD99MdW_tZWClJETnApTwtm7IuQIgKGBRE',
    appId: '1:912364213375:web:7be751bc1e6265248f5b4a',
    messagingSenderId: '912364213375',
    projectId: 'dsspa-73a47',
    authDomain: 'dsspa-73a47.firebaseapp.com',
    databaseURL: 'https://dsspa-73a47-default-rtdb.firebaseio.com',
    storageBucket: 'dsspa-73a47.appspot.com',
    measurementId: 'G-CPTV8WYK6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkn6ddXUieiG6YLHlcOUqzNuJmcduBN5Y',
    appId: '1:912364213375:android:c01f4e52960b1eff8f5b4a',
    messagingSenderId: '912364213375',
    projectId: 'dsspa-73a47',
    databaseURL: 'https://dsspa-73a47-default-rtdb.firebaseio.com',
    storageBucket: 'dsspa-73a47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHGzYofdgILci5bPdCpFMBclhbESBwT0',
    appId: '1:912364213375:ios:54c08693da5a2a7b8f5b4a',
    messagingSenderId: '912364213375',
    projectId: 'dsspa-73a47',
    databaseURL: 'https://dsspa-73a47-default-rtdb.firebaseio.com',
    storageBucket: 'dsspa-73a47.appspot.com',
    androidClientId: '912364213375-1an014i4cbgjrj0obfmsv8fg2ukklhei.apps.googleusercontent.com',
    iosClientId: '912364213375-ss5k5236r9m9roe5ai3s40su2kag3m1c.apps.googleusercontent.com',
    iosBundleId: 'org.sjbdigital.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHGzYofdgILci5bPdCpFMBclhbESBwT0',
    appId: '1:912364213375:ios:54c08693da5a2a7b8f5b4a',
    messagingSenderId: '912364213375',
    projectId: 'dsspa-73a47',
    databaseURL: 'https://dsspa-73a47-default-rtdb.firebaseio.com',
    storageBucket: 'dsspa-73a47.appspot.com',
    androidClientId: '912364213375-1an014i4cbgjrj0obfmsv8fg2ukklhei.apps.googleusercontent.com',
    iosClientId: '912364213375-ss5k5236r9m9roe5ai3s40su2kag3m1c.apps.googleusercontent.com',
    iosBundleId: 'org.sjbdigital.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD99MdW_tZWClJETnApTwtm7IuQIgKGBRE',
    appId: '1:912364213375:web:d9630c9495bd50748f5b4a',
    messagingSenderId: '912364213375',
    projectId: 'dsspa-73a47',
    authDomain: 'dsspa-73a47.firebaseapp.com',
    databaseURL: 'https://dsspa-73a47-default-rtdb.firebaseio.com',
    storageBucket: 'dsspa-73a47.appspot.com',
    measurementId: 'G-8QSKPZ1QRP',
  );
}
